security:
    jwt:
        secret-key: thisprojecthasbeenindevelopmentforalongtimesecret
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutoraspsqldb
    username: niccneimi
    password: securepassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect